# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.2.2'

gem 'active_model_serializers'
gem 'bootsnap', require: false
gem 'has_scope'
gem 'health_check'
gem 'pg', '~> 1.5', '>= 1.5.7'
gem 'puma', '>= 5.0'
gem 'rails', '~> 7.1.3', '>= 7.1.3.4'
gem 'sneakers'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'dotenv-rails'
  gem 'json-schema', '~> 4.3', '>= 4.3.1'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 6.1', '>= 6.1.3'
  gem 'shoulda-matchers', '~> 6.2'
end

group :development do
  gem 'rubocop', '~> 1.65', '>= 1.65.1'
end
